export enum MediaFeatures {
  width = 'width',
  height = 'height',
  aspectRatio = 'aspect-ratio',
  orientation = 'orientation',
  resolution = 'resolution',
  scan = 'scan',
  grid = 'grid',
  update = 'update',
  overflowBlock = 'overflow-block',
  overflowInline = 'overflow-inline',
  color = 'color',
  colorGamut = 'color-gamut',
  colorIndex = 'color-index',
  displayMode = 'display-mode',
  monochrome = 'monochrome',
  invertedColors = 'inverted-colors',
  pointer = 'pointer',
  hover = 'hover',
  anyPointer = 'any-pointer',
  anyHover = 'any-hover',
  lightLevel = 'light-level',
  prefersReducedMotion = 'prefers-reduced-motion',
  prefersReducedTransparency = 'prefers-reduced-transparency',
  prefersContrast = 'prefers-contrast',
  prefersColorScheme = 'prefers-color-scheme',
  scripting = 'scripting'
}

export type MediaFeaturePrefix = 'min-' | 'max-'
